#!/bin/bash

DESC="Start challenge_server.py on boot."
NAME=challenge_server
DAEMON_FOLDER=/opt/challenge
DAEMON=$DAEMON_FOLDER/$NAME.py
DAEMON_ARGS=""
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/challenge

start() {
  start-stop-daemon --start --background --pidfile $PIDFILE --chdir $DAEMON_FOLDER --make-pidfile --exec $DAEMON --quiet
}

stop() {
  kill -TERM `cat $PIDFILE`
  rm $PIDFILE
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: {start|stop|restart}"
    exit 1
    ;;
esac

exit $?